### ISSUE TITLE
Bug: strange remove animation when over an z-index'd element

### ISSUE THREAD

**Issue by jakobploens** [rstacruz/nprogress#138]
I found a strange bug today (not browser related, so might be an issue with CSS itself). When the opacity of the nprogress bar is not 1, the bar is shown behind every other (fixed) element with a z-index > 0. The solution is to just add a z-index to the parent (so #nprogress itself, not only the bar and the spinner elements).

**Comment by syuilo** [comment]
Try:
```css
#nprogress {
  pointer-events: none;

  position: absolute;
  z-index: 1030;
}
```
