### ISSUE TITLE
Add feature to disable page

### ISSUE THREAD

**Issue by pauloanalista** [rstacruz/nprogress#162]
It would be interesting to put a property that allows to disable the background content, so the user could not manipulate the screen controls

**Comment by MikeBull94** [comment]
```css
.nprogress-busy  {
  cursor: wait;

  body {
    pointer-events: none;
  }
}
```
