### ISSUE TITLE
how to change nprogress bar color dynamically

### ISSUE THREAD

**Issue by bharathchandragoud** [rstacruz/nprogress#187]

**Comment by bharathchandragoud** [comment]
i got it. thankyou

**Comment by carlo-fontanos** [comment]
Huh? what's the solution?

**Comment by Anduin2017** [comment]
```css
#nprogress .bar {
background: #29d !important;
}
```

@bharathchandragoud  Your style really helps. Thanks!
