### ISSUE TITLE
Can I move the spinner to the middle of the screen?

### ISSUE THREAD

**Issue by phpcontrols** [rstacruz/nprogress#240]
I wanted to users to know that they need to wait for the spinner to go away before proceed. Possible?

**Comment by tiagozip** [comment]
Great idea, +1!

**Comment by Tof-Arei** [comment]
These CSS overrides seem to be working in my case :
```css
#nprogress .spinner {
    /* ... */
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
#nprogress .spinner-icon {
    /* ... */
    margin: auto;
    /* ... */
}
```
There must be cleaner ways to achieve this, but time is a scarce commodity... ^^'
