### ISSUE TITLE
Error in animation

### ISSUE THREAD

**Issue by renklaf** [rstacruz/nprogress#49]
![nprogress-error](https://f.cloud.github.com/assets/4019130/1298132/345b7ed8-30ef-11e3-854c-266feffbcdf2.png)

NProgress element is appended to a custom div in my application, rather than the body element. 

NProgress CSS override: 

``` css
#nprogress .bar {
  background: $nprogress-color;
  position: fixed;
  z-index: 100;
  width: 100%;
  height: 2px;
}
```
